# PyTorch 

PyTorch is an optimized tensor library for deep learning using GPUs and CPUs.
- Documentation: https://pytorch.org/docs/stable/index.html

## TORCH
The torch package contains data structures for multi-dimensional tensors and defines mathematical operations over these tensors. Additionally, it provides many utilities for efficient serializing of Tensors and arbitrary types, and other useful utilities.

### Tensors
- how to create them
- check their shape
- reshape them

In [17]:
import torch
import numpy as np 

x = torch.Tensor(np.array([[0,1,2,3,4,5,6,7,8,9],[10,11,12,13,14,15,15,17,18, 19]]))

print(f'The tensor is:\n {x}\n')
print(f'The shape of the tensor is:\n {x.shape}\n')
print(f'The rank of the tensor is:\n {len(x.shape)}\n')
print(f'Tensor reshaped:\n {x.reshape(4,1,-1)}\n')

a = torch.Tensor([5,3])
b = torch.Tensor([2,1])
print(f'a*b = {a*b}\n')

c = torch.zeros([3,3])
print(f'c = {c}')
print(f'c shape is {c.shape}')

d = torch.rand([2,5])
print(f'd = {d}')
d = d.view([5,-1])
print(f'd reshaped = {d}')


The tensor is:
 tensor([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [10., 11., 12., 13., 14., 15., 15., 17., 18., 19.]])

The shape of the tensor is:
 torch.Size([2, 10])

The rank of the tensor is:
 2

Tensor reshaped:
 tensor([[[ 0.,  1.,  2.,  3.,  4.]],

        [[ 5.,  6.,  7.,  8.,  9.]],

        [[10., 11., 12., 13., 14.]],

        [[15., 15., 17., 18., 19.]]])

a*b = tensor([10.,  3.])

c = tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
c shape is torch.Size([3, 3])
d = tensor([[0.8687, 0.9379, 0.2478, 0.7329, 0.2808],
        [0.8798, 0.2033, 0.9578, 0.1192, 0.0248]])
d reshaped = tensor([[0.8687, 0.9379],
        [0.2478, 0.7329],
        [0.2808, 0.8798],
        [0.2033, 0.9578],
        [0.1192, 0.0248]])


## Shape of a CNN input

The shape of a CNN input typically has a length of four. This means that we have a rank-4 tensor with four axes.

[ B, C, H, W ]:[Batch, Channels, Height, Width]

- B: Image batches
- C: Typical values here are 3 for RGB images or 1 if we are working with grayscale images.
- H: Image height
- W: Image width

link：https://www.jianshu.com/p/c47358d70d01

### Operations between tensors 
- They have to be allocated in the same device (cpu, gpu)

In [40]:
x = torch.tensor([2,5])
y = torch.tensor([8.0,4.5])
z = torch.tensor([1,1], dtype = torch.float64)

print(f'x dtype: {x.dtype}, located in {x.device}')
print(f'y dtype: {y.dtype}, located in {y.device}')
print(f'z dtype: {z.dtype}, located in {z.device}')

try: 
    print(x + y)
    print("no problems!")
except Exception as e:
    print(e) 


x dtype: torch.int64, located in cpu
y dtype: torch.float32, located in cpu
z dtype: torch.float64, located in cpu
tensor([10.0000,  9.5000])
no problems!


In [44]:
m = y.cuda()
print(f'm dtype: {m.dtype}, located in {m.device}\n')

try: 
    print(x + m)
    print("no problems!")
except Exception as e:
    print("There was a problem:")
    print(e) 


m dtype: torch.float32, located in cuda:0

There was a problem:
Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!


## Different ways of creating tensors

Sharing memory for performance: copy vs share

Share data
- **torch.as_tensor()** <- prefered
- torch.from_numpy()

Copy data
- **torch.tensor()** <- prefered
- torch.Tensor()

In [47]:
t = np.array([[1,2],[3,4]])

tensor1 = torch.as_tensor(t)
t[0,0] = 1000

print(tensor1)

tensor([[1000,    2],
        [   3,    4]], dtype=torch.int32)


In [48]:
t = np.array([[1,2],[3,4]])

tensor1 = torch.tensor(t)
t[0,0] = 1000

print(tensor1)

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)


## Flatten function 

In [50]:
def flatten(t):
    t = t.reshape(1,-1)
    t = t.squeeze()
    return t

t = torch.tensor([[1,2],[3,4],[5,6]])

print(f't is {t}, which shape is {t.shape}')
print(f'flatten t is {flatten(t)}, which shape is {flatten(t).shape}')

t is tensor([[1, 2],
        [3, 4],
        [5, 6]]), which shape is torch.Size([3, 2])
flatten t is tensor([1, 2, 3, 4, 5, 6]), which shape is torch.Size([6])


## Flatten built in function

In [60]:
t = torch.tensor([[[1,2],[3,4],[5,6]], [[1,2],[3,4],[5,6]]])

t = t.flatten(start_dim=1)
print(f'flatten t is\n {t}\n which shape is {t.shape}')

flatten t is
 tensor([[1, 2, 3, 4, 5, 6],
        [1, 2, 3, 4, 5, 6]])
 which shape is torch.Size([2, 6])
